//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cursomvcapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int id_galeria { get; set; }
        public string foto_name { get; set; }
        public string foto { get; set; }
        public int id_identificador { get; set; }
    }
}
